### ISSUE TITLE
Error "Cannot find module 'fs/package.json' when using AWS SDK

### ISSUE THREAD

**Issue by andersforsell** [cfware/babel-plugin-template-html-minifier#2]
See https://github.com/web-padawan/polymer3-webpack-starter/issues/10

when building with `npm run build` with the extra dependencies:
```
    "amazon-cognito-identity-js": "^2.0.27",
    "aws-amplify": "^1.1.1",
    "aws-appsync": "^1.3.4",
```
I get this error:
```
ERROR in ./node_modules/aws-sdk/lib/util.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module 'fs/package.json'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (C:\git\polymer3-webpack-starter\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at getPkgMain (C:\git\polymer3-webpack-starter\node_modules\babel-plugin-template-html-minifier\index.js:16:18)
    at bareName (C:\git\polymer3-webpack-starter\node_modules\babel-plugin-template-html-minifier\index.js:25:18)
    at getModuleConfig (C:\git\polymer3-webpack-starter\node_modules\babel-plugin-template-html-minifier\index.js:43:25)
    at PluginPass.CallExpression (C:\git\polymer3-webpack-starter\node_modules\babel-plugin-template-html-minifier\index.js:96:27)
    at newFn (C:\git\polymer3-webpack-starter\node_modules\@babel\traverse\lib\visitors.js:193:21)
    at NodePath._call (C:\git\polymer3-webpack-starter\node_modules\@babel\traverse\lib\path\context.js:53:20)
    at NodePath.call (C:\git\polymer3-webpack-starter\node_modules\@babel\traverse\lib\path\context.js:40:17)
    at NodePath.visit (C:\git\polymer3-webpack-starter\node_modules\@babel\traverse\lib\path\context.js:88:12)
    at TraversalContext.visitQueue (C:\git\polymer3-webpack-starter\node_modules\@babel\traverse\lib\context.js:118:16)
    at TraversalContext.visitSingle (C:\git\polymer3-webpack-starter\node_modules\@babel\traverse\lib\context.js:90:19)
    at TraversalContext.visit (C:\git\polymer3-webpack-starter\node_modules\@babel\traverse\lib\context.js:146:19)
    at Function.traverse.node (C:\git\polymer3-webpack-starter\node_modules\@babel\traverse\lib\index.js:94:17)
    at NodePath.visit (C:\git\polymer3-webpack-starter\node_modules\@babel\traverse\lib\path\context.js:95:18)
    at TraversalContext.visitQueue (C:\git\polymer3-webpack-starter\node_modules\@babel\traverse\lib\context.js:118:16)
    at TraversalContext.visitMultiple (C:\git\polymer3-webpack-starter\node_modules\@babel\traverse\lib\context.js:85:17)
    at TraversalContext.visit (C:\git\polymer3-webpack-starter\node_modules\@babel\traverse\lib\context.js:144:19)
    at Function.traverse.node (C:\git\polymer3-webpack-starter\node_modules\@babel\traverse\lib\index.js:94:17)
    at NodePath.visit (C:\git\polymer3-webpack-starter\node_modules\@babel\traverse\lib\path\context.js:95:18)
    at TraversalContext.visitQueue (C:\git\polymer3-webpack-starter\node_modules\@babel\traverse\lib\context.js:118:16)
    at TraversalContext.visitMultiple (C:\git\polymer3-webpack-starter\node_modules\@babel\traverse\lib\context.js:85:17)
    at TraversalContext.visit (C:\git\polymer3-webpack-starter\node_modules\@babel\traverse\lib\context.js:144:19)
    at Function.traverse.node (C:\git\polymer3-webpack-starter\node_modules\@babel\traverse\lib\index.js:94:17)
    at NodePath.visit (C:\git\polymer3-webpack-starter\node_modules\@babel\traverse\lib\path\context.js:95:18)
    at TraversalContext.visitQueue (C:\git\polymer3-webpack-starter\node_modules\@babel\traverse\lib\context.js:118:16)
    at TraversalContext.visitSingle (C:\git\polymer3-webpack-starter\node_modules\@babel\traverse\lib\context.js:90:19)
    at TraversalContext.visit (C:\git\polymer3-webpack-starter\node_modules\@babel\traverse\lib\context.js:146:19)
    at Function.traverse.node (C:\git\polymer3-webpack-starter\node_modules\@babel\traverse\lib\index.js:94:17)
    at NodePath.visit (C:\git\polymer3-webpack-starter\node_modules\@babel\traverse\lib\path\context.js:95:18)
    at TraversalContext.visitQueue (C:\git\polymer3-webpack-starter\node_modules\@babel\traverse\lib\context.js:118:16)
    at TraversalContext.visitMultiple (C:\git\polymer3-webpack-starter\node_modules\@babel\traverse\lib\context.js:85:17)
    at TraversalContext.visit (C:\git\polymer3-webpack-starter\node_modules\@babel\traverse\lib\context.js:144:19)
    at Function.traverse.node (C:\git\polymer3-webpack-starter\node_modules\@babel\traverse\lib\index.js:94:17)
 @ ./node_modules/aws-sdk/lib/core.js 1:48-65
 @ ./node_modules/aws-sdk/clients/s3.js
 @ ./node_modules/@aws-amplify/storage/lib/Storage.js
 @ ./node_modules/@aws-amplify/storage/lib/index.js
 @ ./node_modules/aws-amplify/lib/index.js
 @ ./src/aws-appsync.js
 @ ./src/mint-appsync.js
 @ ./src/app/starter-app.js
 @ ./src/index.js
Child HtmlWebpackCompiler:
     1 asset
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html 3.78 KiB {0} [built]
    [2] (webpack)/buildin/global.js 239 bytes {0} [built]
    [3] (webpack)/buildin/module.js 399 bytes {0} [built]
        + 1 hidden module
```

**Comment by web-padawan** [comment]
Copy-pasting my comment from the original issue about the line where it happens: https://github.com/goto-bus-stop/babel-plugin-template-html-minifier/blob/234528d3a0f52f69a0563bcfe39343ac5ea49959/index.js#L16

**Comment by coreyfarrell** [comment]
@andersforsell I've posted #3 to fix this issue.  It passes my own tests but could you also test against your own project?

You should be able to test by using `npm install 'coreyfarrell/babel-plugin-template-html-minifier#tolerate-builtin'` on your project to install directly from the github branch, just remember to switch back to semver after as the branch will be deleted once this fix is released.

**Comment by andersforsell** [comment]
@coreyfarrell Thanks for the quick response. I can confirm that #3  fixes the issue.
