### ISSUE TITLE
[Bug] Plugin fails with css`... ${unsafeCSS(...)}`

### ISSUE THREAD

**Issue by kkimdev** [cfware/babel-plugin-template-html-minifier#23]
Example:

```css
import {
  css,
  unsafeCSS,
} from 'lit-element/lit-element.js';
const THUMBNAIL_WIDTH = '210px';
const THUMBNAIL_HEIGHT = '118px';
css`
      :root {
        --thumbnail-width: ${unsafeCSS(THUMBNAIL_WIDTH)};
        --thumbnail-height: ${unsafeCSS(THUMBNAIL_WIDTH)};
      }
    `;
```

Log:
```
ERROR in ./src/m19g-game-list.js
Module build failed (from ./dev_tool/node_modules/babel-loader/lib/index.js):
Error: html-minifier deleted something major, cannot proceed.
    at minify (/root/winhome/projects/game/client/dev_tool/node_modules/babel-plugin-template-html-minifier/index.js:78:9)
    at handleSimple (/root/winhome/projects/game/client/dev_tool/node_modules/babel-plugin-template-html-minifier/index.js:102:3)
    at PluginPass.TaggedTemplateExpression (/root/winhome/projects/game/client/dev_tool/node_modules/babel-plugin-template-html-minifier/index.js:196:6)
    at newFn (/root/winhome/projects/game/client/dev_tool/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/root/winhome/projects/game/client/dev_tool/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/root/winhome/projects/game/client/dev_tool/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/root/winhome/projects/game/client/dev_tool/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/root/winhome/projects/game/client/dev_tool/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/root/winhome/projects/game/client/dev_tool/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/root/winhome/projects/game/client/dev_tool/node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (/root/winhome/projects/game/client/dev_tool/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/root/winhome/projects/game/client/dev_tool/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/root/winhome/projects/game/client/dev_tool/node_modules/@babel/traverse/lib/contex.js:118:16)
    at TraversalContext.visitMultiple (/root/winhome/projects/game/client/dev_tool/node_modules/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (/root/winhome/projects/game/client/dev_tool/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (/root/winhome/projects/game/client/dev_tool/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/root/winhome/projects/game/client/dev_tool/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/root/winhome/projects/game/client/dev_tool/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/root/winhome/projects/game/client/dev_tool/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/root/winhome/projects/game/client/dev_tool/node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (/root/winhome/projects/game/client/dev_tool/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/root/winhome/projects/game/client/dev_tool/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/root/winhome/projects/game/client/dev_tool/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/root/winhome/projects/game/client/dev_tool/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/root/winhome/projects/game/client/dev_tool/node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (/root/winhome/projects/game/client/dev_tool/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/root/winhome/projects/game/client/dev_tool/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/root/winhome/projects/game/client/dev_tool/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitMultiple (/root/winhome/projects/game/client/dev_tool/node_modules/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (/root/winhome/projects/game/client/dev_tool/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (/root/winhome/projects/game/client/dev_tool/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/root/winhome/projects/game/client/dev_tool/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/root/winhome/projects/game/client/dev_tool/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitMultiple (/root/winhome/projects/game/client/dev_tool/node_modules/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (/root/winhome/projects/game/client/dev_tool/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (/root/winhome/projects/game/client/dev_tool/node_modules/@babel/traverse/lib/index.js:94:17)
 @ ./src/m19g-main-ui.js 35:0-29
 @ ./src/m19g-app.js
```

**Comment by kkimdev** [comment]
nvm, false bug report.
