### ISSUE TITLE
Error: html-minifier deleted something major, cannot proceed.

### ISSUE THREAD

**Issue by paales** [cfware/babel-plugin-template-html-minifier#24]
```
    ERROR in ./node_modules/@reachdigital/configurable-bundle/configurable-bundle.ts
    Module build failed (from ./node_modules/babel-loader/lib/index.js):
    Error: html-minifier deleted something major, cannot proceed.
        at minify (.../node_modules/babel-plugin-template-html-minifier/index.js:78:9)
        at handleSimple (.../node_modules/babel-plugin-template-html-minifier/index.js:102:3)
        at PluginPass.TaggedTemplateExpression (.../node_modules/babel-plugin-template-html-minifier/index.js:196:6)
        at newFn (.../node_modules/@babel/traverse/lib/visitors.js:193:21)
        at NodePath._call (.../node_modules/@babel/traverse/lib/path/context.js:53:20)
        at NodePath.call (.../node_modules/@babel/traverse/lib/path/context.js:40:17)
        at NodePath.visit (.../node_modules/@babel/traverse/lib/path/context.js:88:12)
        at TraversalContext.visitQueue (.../node_modules/@babel/traverse/lib/context.js:118:16)
        at TraversalContext.visitSingle (.../node_modules/@babel/traverse/lib/context.js:90:19)
        at TraversalContext.visit (.../node_modules/@babel/traverse/lib/context.js:146:19)
        at Function.traverse.node (.../node_modules/@babel/traverse/lib/index.js:94:17)
        at NodePath.visit (.../node_modules/@babel/traverse/lib/path/context.js:95:18)
        at TraversalContext.visitQueue (.../node_modules/@babel/traverse/lib/context.js:118:16)
        at TraversalContext.visitMultiple (.../node_modules/@babel/traverse/lib/context.js:85:17)
        at TraversalContext.visit (.../node_modules/@babel/traverse/lib/context.js:144:19)
        at Function.traverse.node (.../node_modules/@babel/traverse/lib/index.js:94:17)
        at NodePath.visit (.../node_modules/@babel/traverse/lib/path/context.js:95:18)
        at TraversalContext.visitQueue (.../node_modules/@babel/traverse/lib/context.js:118:16)
        at TraversalContext.visitSingle (.../node_modules/@babel/traverse/lib/context.js:90:19)
        at TraversalContext.visit (.../node_modules/@babel/traverse/lib/context.js:146:19)
        at Function.traverse.node (.../node_modules/@babel/traverse/lib/index.js:94:17)
        at NodePath.visit (.../node_modules/@babel/traverse/lib/path/context.js:95:18)
        at TraversalContext.visitQueue (.../node_modules/@babel/traverse/lib/context.js:118:16)
        at TraversalContext.visitSingle (.../node_modules/@babel/traverse/lib/context.js:90:19)
        at TraversalContext.visit (.../node_modules/@babel/traverse/lib/context.js:146:19)
        at Function.traverse.node (.../node_modules/@babel/traverse/lib/index.js:94:17)
        at NodePath.visit (.../node_modules/@babel/traverse/lib/path/context.js:95:18)
        at TraversalContext.visitQueue (.../node_modules/@babel/traverse/lib/context.js:118:16)
        at TraversalContext.visitMultiple (.../node_modules/@babel/traverse/lib/context.js:85:17)
        at TraversalContext.visit (.../node_modules/@babel/traverse/lib/context.js:144:19)
        at Function.traverse.node (.../node_modules/@babel/traverse/lib/index.js:94:17)
        at NodePath.visit (.../node_modules/@babel/traverse/lib/path/context.js:95:18)
        at TraversalContext.visitQueue (.../node_modules/@babel/traverse/lib/context.js:118:16)
        at TraversalContext.visitMultiple (.../node_modules/@babel/traverse/lib/context.js:85:17)
        at TraversalContext.visit (.../node_modules/@babel/traverse/lib/context.js:144:19)
        at Function.traverse.node (.../node_modules/@babel/traverse/lib/index.js:94:17)
     @ ./webcomponents/webcomponents.js 32:0-66
     @ ./app/design/frontend/ReachDigital/sightful/web/index.js
     @ multi ./app/design/frontend/ReachDigital/sightful/web/index.js
```

I'm not sure if the line numbers are mapping perfectly but on line 32 of my webcomponents.js i'm imporing a polymer 3 component, which has the following contents:

in `./webcomponents/webcomponents.js`:
```
import "./src/usps-list/usps-list.js"
```

in `./src/usps-list/usps-list.js`
```
/*
 * Copyright © Reach Digital (https://www.reachdigital.io/)
 * See LICENSE.txt for license details.
 */
import { PolymerElement, html } from '@polymer/polymer/polymer-element.js'
import {DomRepeat} from '@polymer/polymer/lib/elements/dom-repeat.js'
import { beforeNextRender, afterNextRender } from '@polymer/polymer/lib/utils/render-status.js';
import { FlattenedNodesObserver } from '@polymer/polymer/lib/utils/flattened-nodes-observer.js'
import "@polymer/iron-media-query/iron-media-query.js"
import "@reachdigital/polyfill-loader/polyfill-loader.js"
import "@reachdigital/inner-html/inner-html.js"

class UspsList extends PolymerElement {
  static get template () {
    return html`
      <style>
        :host {
          color: var(--usps-list-color, var(--primary, black));
          margin-top: var(--usps-list-margin-top, 0);
          margin-bottom: var(--usps-list-margin-bottom, var(--spacing-md));
          display: block;
        }
        :host > div {
          display: var(--usps-display, flex);
          flex-direction: var(--usps-flex-direction, row);
          flex-wrap: nowrap;
          justify-content: var(--usps-justify-content, space-between);
          padding:  0;
          margin: 0;
  
        }
        :host([visible-items="1"]) > div {
          justify-content: space-around;
        }
        div > div {
          list-style: none;
          white-space: nowrap;
        }
        .hidden {
          display: block;
          width: 0;
          overflow: hidden;
          position: absolute;
        }
        
        a {
          color: inherit;
        }
      </style>
  
      <div>
        <template is="dom-repeat" items="[[usps]]">
          <div class="usp"><span><inner-html html="[[item]]"></inner-html></span></div>
        </template>
      </div>
    `;
  }

  static get properties() {
    return {
      /**
       * @type {array}
       */
      usps: Array,
      children: Array,
      visibleItems: {
        type: Number,
        reflectToAttribute: true
      }
    }
  }

  constructor() {
    super();

    this.__polyfillLoader = document.createElement('polyfill-loader');

  }

  /* Called when the element is inserted into a document */
  connectedCallback() {
    super.connectedCallback();

    this.__polyfillLoader.all(['ResizeObserver']).then(() => {
      this.__resizeObserver = new window.ResizeObserver((entries) => {
        entries.forEach((entry) => this._renderUSPs(entry))
      })

      this.__resizeObserver.observe(this)
    });

    beforeNextRender(this, () => {
      let nodes = FlattenedNodesObserver.getFlattenedNodes(this).filter((node) => (node.nodeType === Node.ELEMENT_NODE && node.id !== "ct-field-"));
      if(!nodes.length) {
        return;
      }

      nodes.forEach((node) => {
        if(!node.classList.contains('ct-field-repeater_fields')) {
          return;
        }
        this.usps = [...node.querySelectorAll('div.ct-view-usp_repeater_field')].map(el => el.querySelector('.ct-field-area p').innerHTML).filter((elem) => elem);
      })
    })
  }

  _renderUSPs(entry) {
    let listItems = [...this.shadowRoot.querySelectorAll('.usp')];//.reverse();

    let listItemsWithWidth = [];
    listItems.forEach((item) => {
      listItemsWithWidth.push({'elem': item, 'width': item.querySelector('span').offsetWidth});
    });

    let availableSpace = entry.contentRect.width;
    let totalWidth = 0;
    let allowedItemCount = listItemsWithWidth.length;

    for(let i = 0; i < listItemsWithWidth.length; i++) {
      if(i != 0) {
        // add spacing so items never touch
        totalWidth += 10;
      }
      totalWidth += listItemsWithWidth[i].width;
      if(totalWidth > availableSpace) {
        allowedItemCount = i;
        break;
      }
    }

    this.visibleItems = allowedItemCount;
    this._hideItems(allowedItemCount, listItemsWithWidth);
  }

  _hideItems(allowedItemCount, items) {
    for(let i = allowedItemCount; i < items.length; i++) {
      items[i].elem.classList.add('hidden');
    }
    for(let i = 0; i<allowedItemCount; i++) {
      items[i].elem.classList.remove('hidden');
    }
  }

  disconnectedCallback() {
    super.disconnectedCallback()

    // Unobserve resizing if element is removed
    this.__polyfillLoader.get('ResizeObserver').then(() => {
      this.__resizeObserver.unobserve(this)
      this.__resizeObserver.disconnect();
    });
  }
}

customElements.define('usps-list', UspsList);
```

**Comment by paales** [comment]
The error lines reported in my stack trace didn't match. That is solved by: https://github.com/cfware/babel-plugin-template-html-minifier/pull/25

Issue was that my template contained a comment with JS:

```
<!--<input type="checkbox" name="debug" @change=${this.toggleDebug} />-->`
```

And stripComments was enabled, which also stripped the JS stuff

**Comment by paales** [comment]
https://github.com/open-wc/open-wc/blob/master/packages/building-webpack/modern-and-legacy-config.js#L67
